name: Build
on:
    - push

jobs:
  build-macos:
    name: Build (macOS)
    runs-on: macos-10.13
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Bundle
          run: bundle install
        - name: Set Node.js version
          run: |
              bundle exec ruby -e 'puts Libv8Node::NODE_VERSION' | tee node_version
        - name: Download Node.js
          run: |
              ./download-node 12.18.4
        - name: Extract Node.js
          run: |
              ./extract-node 12.18.4
        - name: Build V8
          run: |
              ./build-libv8 12.18.4
        - name: Build Monolith
          run: |
              ./build-monolith 12.18.4
        - name: Inject V8
          run: |
              ./inject-libv8 12.18.4
        - name: Build gem
          run: |
              bundle exec rake binary
        - name: Upload V8
          uses: actions/upload-artifact@v1
          with:
            name: v8-x86_64-darwin19
            path: vendor
        - name: Upload gem
          uses: actions/upload-artifact@v1
          with:
            name: gem-x86_64-darwin19
            path: pkg
  build-linux-glibc:
    name: Build (Linux glibc)
    runs-on: ubuntu-20.04
    container: ruby:2.7
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Bundle
          run: bundle install
        - name: Download Node.js
          run: |
              ./download-node 12.18.4
        - name: Extract Node.js
          run: |
              ./extract-node 12.18.4
        - name: Build V8
          run: |
              ./build-libv8 12.18.4
        - name: Build Monolith
          run: |
              ./build-monolith 12.18.4
        - name: Inject V8
          run: |
              ./inject-libv8 12.18.4
        - name: Build gem
          run: |
              bundle exec rake binary
        - name: Upload V8
          uses: actions/upload-artifact@v1
          with:
            name: v8-x86_64-linux-glibc
            path: vendor
        - name: Upload gem
          uses: actions/upload-artifact@v1
          with:
            name: gem-x86_64-linux-glibc
            path: pkg
  build-linux-musl:
    name: Build (Linux musl)
    runs-on: ubuntu-20.04
    container: ruby:2.7-alpine
    steps:
        - name: Install system dependencies
          run: apk add --no-cache build-base bash python2 python3 git curl tar clang binutils-gold
        - name: Checkout
          uses: actions/checkout@v2
        - name: Bundle
          run: bundle install
        - name: Download Node.js
          run: |
              ./download-node 12.18.4
        - name: Extract Node.js
          run: |
              ./extract-node 12.18.4
        - name: Build V8
          run: |
              ./build-libv8 12.18.4
        - name: Build Monolith
          run: |
              ./build-monolith 12.18.4
        - name: Inject V8
          run: |
              ./inject-libv8 12.18.4
        - name: Build gem
          run: |
              bundle exec rake binary
        - name: Prepare artifacts
          run: |
              mkdir -p ${{ runner.temp }}/workspace
              cp -Rv pkg ${{ runner.temp }}/workspace/
              cp -Rv vendor ${{ runner.temp }}/workspace/
        - name: Upload V8
          uses: actions/upload-artifact@v1
          with:
            name: v8-x86_64-linux-musl
            path: vendor
        - name: Upload gem
          uses: actions/upload-artifact@v1
          with:
            name: gem-x86_64-linux-musl
            path: pkg
